#!/usr/bin/env python3
"""Generate the AMQP 1.0 declared surface as Lean data from the pinned artifacts.

    scripts/gen-oasis-lean.py            # write lean/Generated/Oasis/*.lean
    scripts/gen-oasis-lean.py --check    # verify the committed modules are current

The OASIS artifacts carry their definitions in machine-readable form — `type`,
`field`, `choice`, `descriptor`, `encoding`, `definition` — so the specification
never transcribes a descriptor code, a field order, a mandatory flag or a default
by hand. Those are data, reviewed by diffing against the artifact text, and this
generator is the only writer.

Generation is deterministic: same pinned bytes in, byte-identical Lean out. The
fidelity contract (`tests/contracts/s0_tables_fidelity.sh`) checks that, and
checks that mutating a descriptor code in a scratch copy of an artifact changes
the generated output.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tempfile
from pathlib import Path
from xml.etree import ElementTree

ARTIFACT_GLOB = "amqp-core-*-v1.0-os.xml"
NAMESPACE = "SpecAMQP.Generated.Oasis"
HEADER = """\
-- Generated by `scripts/gen-oasis-lean.py` from the pinned OASIS artifacts.
-- Do not edit: regenerate instead. The artifact byte identities this file was
-- derived from are recorded in `toolchain/sources.toml`, and the provenance
-- summary is `lean/Generated/Oasis/provenance.json`.
"""


def die(message: str) -> "None":
    print(f"gen-oasis-lean: {message}", file=sys.stderr)
    raise SystemExit(1)


def clean(value: str) -> str:
    """Collapse whitespace in human-readable attribute text (labels)."""
    return " ".join(value.split())


def lean_string(value: str) -> str:
    """A Lean string literal for arbitrary artifact text."""
    out = ['"']
    for character in value:
        if character == "\\":
            out.append("\\\\")
        elif character == '"':
            out.append('\\"')
        elif character == "\n":
            out.append("\\n")
        elif character == "\t":
            out.append("\\t")
        elif ord(character) < 0x20:
            out.append(f"\\u{{{ord(character):04x}}}")
        else:
            out.append(character)
    out.append('"')
    return "".join(out)


def lean_option(value: str | None) -> str:
    return "none" if value is None else f"some {lean_string(value)}"


def lean_list(values: list[str]) -> str:
    return "[" + ", ".join(lean_string(value) for value in values) + "]"


def parse_code(code: str | None) -> tuple[int, int] | None:
    """Parse a descriptor code of the form `0x00000000:0x00000010`."""
    if not code or ":" not in code:
        return None
    domain, descriptor = code.split(":", 1)
    try:
        return int(domain, 16), int(descriptor, 16)
    except ValueError:
        return None


def named_path(ancestors: list[ElementTree.Element]) -> str:
    """`tag:name` chain of the named elements among the ancestors, root first."""
    return "/".join(
        f"{node.tag}:{node.attrib['name']}"
        for node in ancestors
        if node.attrib.get("name")
    )


def nearest_type_name(ancestors: list[ElementTree.Element]) -> str:
    for node in reversed(ancestors):
        if node.tag == "type":
            return node.attrib.get("name", "")
    return ""


def field_index(ancestors: list[ElementTree.Element], element: ElementTree.Element) -> int:
    """1-based position of a field among its type's fields, as the artifact orders them."""
    if not ancestors:
        return 0
    fields = [child for child in ancestors[-1] if child.tag == "field"]
    return fields.index(element) + 1 if element in fields else 0


def walk(
    element: ElementTree.Element,
    ancestors: list[ElementTree.Element],
    artifact: str,
    records: list[dict],
) -> None:
    """Collect declared-surface records in document order, carrying ancestry."""
    context = ancestors + [element]
    attributes = element.attrib
    record: dict | None = None

    if element.tag == "definition" and "name" in attributes:
        record = {
            "kind": "constant",
            "name": attributes["name"],
            "value": attributes.get("value", ""),
            "label": clean(attributes.get("label", "")),
            "artifact": artifact,
        }
    elif element.tag == "encoding" and "code" in attributes:
        record = {
            "kind": "encoding",
            "name": attributes.get("name"),
            "code": int(attributes["code"], 16),
            "category": attributes.get("category", ""),
            "width": int(attributes.get("width", "0")),
            "label": clean(attributes.get("label", "")),
            "owner": nearest_type_name(ancestors),
            "path": named_path(context),
            "artifact": artifact,
        }
    elif element.tag == "descriptor":
        parsed = parse_code(attributes.get("code"))
        if parsed:
            record = {
                "kind": "descriptor",
                "name": attributes.get("name", ""),
                "domain": parsed[0],
                "code": parsed[1],
                "ownerPath": named_path(ancestors),
                "artifact": artifact,
            }
    elif element.tag == "type" and "name" in attributes and "class" in attributes:
        record = {
            "kind": "type",
            "name": attributes["name"],
            "class": attributes["class"],
            "source": attributes.get("source"),
            "provides": [
                part.strip()
                for part in attributes.get("provides", "").split(",")
                if part.strip()
            ],
            "label": clean(attributes.get("label", "")),
            "path": named_path(context),
            "artifact": artifact,
        }
    elif element.tag == "field" and "name" in attributes:
        record = {
            "kind": "field",
            "name": attributes["name"],
            "owner": nearest_type_name(ancestors),
            "ownerPath": named_path(ancestors),
            "index": field_index(ancestors, element),
            "type": attributes.get("type", ""),
            "mandatory": attributes.get("mandatory") == "true",
            "default": attributes.get("default"),
            "multiple": attributes.get("multiple") == "true",
            "requires": attributes.get("requires"),
            "label": clean(attributes.get("label", "")),
            "artifact": artifact,
        }
    elif element.tag == "choice" and "name" in attributes:
        record = {
            "kind": "choice",
            "name": attributes["name"],
            "value": attributes.get("value", ""),
            "ownerPath": named_path(ancestors),
            "artifact": artifact,
        }

    if record:
        records.append(record)
    for child in element:
        walk(child, context, artifact, records)


def load(artifacts: Path) -> tuple[list[dict], dict[str, str]]:
    files = sorted(artifacts.glob(ARTIFACT_GLOB))
    if not files:
        die(f"no {ARTIFACT_GLOB} artifacts found in {artifacts}")
    records: list[dict] = []
    digests: dict[str, str] = {}
    for path in files:
        digests[path.name] = hashlib.sha256(path.read_bytes()).hexdigest()
        walk(ElementTree.parse(path).getroot(), [], path.name, records)
    return records, digests


def render_constants(records: list[dict]) -> str:
    rows = [
        f"  {{ name := {lean_string(r['name'])}, value := {lean_string(r['value'])}, "
        f"label := {lean_string(r['label'])}, artifact := {lean_string(r['artifact'])} }},"
        for r in sorted(records, key=lambda r: r["name"])
    ]
    return f"""{HEADER}
namespace {NAMESPACE}

/-- A constant the specification text cites by name, e.g. `MIN-MAX-FRAME-SIZE`.
Clauses that reference one resolve to its `value`, so a change of value changes
the clause text and invalidates that clause's disposition. -/
structure Constant where
  name : String
  value : String
  label : String
  artifact : String
deriving Repr, DecidableEq

def constants : List Constant := [
{chr(10).join(rows)}
]

/-- Look up a constant by name. -/
def constantValue? (name : String) : Option String :=
  (constants.find? (fun entry => entry.name == name)).map (fun entry => entry.value)

end {NAMESPACE}
"""


def render_types(records: list[dict], descriptors: list[dict]) -> str:
    by_owner = {
        (d["artifact"], d["ownerPath"]): d for d in descriptors
    }
    rows = []
    for r in sorted(records, key=lambda r: (r["artifact"], r["name"])):
        descriptor = by_owner.get((r["artifact"], r["path"]))
        descriptor_expr = (
            f"some {{ name := {lean_string(descriptor['name'])}, "
            f"domain := {descriptor['domain']}, code := {descriptor['code']} }}"
            if descriptor
            else "none"
        )
        rows.append(
            f"  {{ name := {lean_string(r['name'])}, typeClass := .{r['class']}, "
            f"source := {lean_option(r['source'])}, provides := {lean_list(r['provides'])}, "
            f"descriptor := {descriptor_expr}, label := {lean_string(r['label'])}, "
            f"path := {lean_string(r['path'])}, artifact := {lean_string(r['artifact'])} }},"
        )
    return f"""{HEADER}
namespace {NAMESPACE}

/-- The three kinds of definition the AMQP definition language declares. -/
inductive TypeClass where
  | primitive
  | restricted
  | composite
deriving Repr, DecidableEq

/-- A described-type descriptor: the domain/code pair that names a type on the
wire, e.g. `amqp:open:list` = `0x00000000:0x00000010`. -/
structure Descriptor where
  name : String
  domain : Nat
  code : Nat
deriving Repr, DecidableEq

/-- A declared type. `source` is the underlying type for restricted and composite
types; `provides` names the semantic role the type fills (frame, sasl-frame,
error-condition, delivery-state, ...). -/
structure TypeDecl where
  name : String
  typeClass : TypeClass
  source : Option String
  provides : List String
  descriptor : Option Descriptor
  label : String
  /-- Anchor path in the artifact, e.g. `amqp:transport/section:performatives/type:open`.
  It is the stable link between a declaration and the clause ledger. -/
  path : String
  artifact : String
deriving Repr, DecidableEq

def types : List TypeDecl := [
{chr(10).join(rows)}
]

/-- Descriptor names are wire identity: this is the lookup the codec tables use
instead of a hand-written match on literals. -/
def descriptorOf (name : String) : Option Descriptor :=
  (types.find? (fun entry => entry.name == name)).bind (fun entry => entry.descriptor)

end {NAMESPACE}
"""


def render_fields(records: list[dict]) -> str:
    rows = []
    for r in sorted(records, key=lambda r: (r["artifact"], r["ownerPath"], r["index"])):
        rows.append(
            f"  {{ owner := {lean_string(r['owner'])}, ownerPath := {lean_string(r['ownerPath'])}, "
            f"index := {r['index']}, name := {lean_string(r['name'])}, "
            f"typeName := {lean_string(r['type'])}, mandatory := {str(r['mandatory']).lower()}, "
            f"defaultValue := {lean_option(r['default'])}, "
            f"multiple := {str(r['multiple']).lower()}, "
            f"requires := {lean_option(r['requires'])}, label := {lean_string(r['label'])}, "
            f"artifact := {lean_string(r['artifact'])} }},"
        )
    return f"""{HEADER}
namespace {NAMESPACE}

/-- A field of a composite type, in wire order. `defaultValue` records the
default the specification declares, which is part of the type's behaviour rather
than an implementation choice. -/
structure FieldDecl where
  owner : String
  ownerPath : String
  index : Nat
  name : String
  typeName : String
  mandatory : Bool
  defaultValue : Option String
  multiple : Bool
  requires : Option String
  label : String
  artifact : String
deriving Repr, DecidableEq

def fields : List FieldDecl := [
{chr(10).join(rows)}
]

/-- The fields of one type, in the order the artifact declares them. -/
def fieldsOf (ownerPath : String) : List FieldDecl :=
  fields.filter (fun entry => entry.ownerPath == ownerPath)

/-- The mandatory fields of one type: the prefix a decoder must see, and the
reason trailing absent fields can be omitted from an encoding. -/
def mandatoryFields (ownerPath : String) : List FieldDecl :=
  (fieldsOf ownerPath).filter (fun entry => entry.mandatory)

end {NAMESPACE}
"""


def render_encodings(records: list[dict]) -> str:
    rows = []
    for r in sorted(records, key=lambda r: r["code"]):
        rows.append(
            f"  {{ code := {r['code']}, name := {lean_option(r['name'])}, "
            f"category := .{r['category']}, width := {r['width']}, "
            f"owner := {lean_string(r['owner'])}, label := {lean_string(r['label'])} }},"
        )
    return f"""{HEADER}
namespace {NAMESPACE}

/-- The four encoding categories the type system defines. -/
inductive Category where
  | fixed
  | variable
  | compound
  | array
deriving Repr, DecidableEq

/-- One encoding of one primitive type: the constructor octet a decoder sees
first, its category, and the width of its size or length field. -/
structure EncodingDecl where
  code : Nat
  name : Option String
  category : Category
  width : Nat
  owner : String
  label : String
deriving Repr, DecidableEq

def encodings : List EncodingDecl := [
{chr(10).join(rows)}
]

/-- The encoding a constructor octet selects, or `none` for an unassigned octet,
which is a decode error rather than an unknown value. -/
def encodingOf (code : Nat) : Option EncodingDecl :=
  encodings.find? (fun entry => entry.code == code)

end {NAMESPACE}
"""


def render_choices(records: list[dict], types: list[dict]) -> str:
    rows = []
    for r in sorted(records, key=lambda r: (r["artifact"], r["ownerPath"], r["value"])):
        rows.append(
            f"  {{ ownerPath := {lean_string(r['ownerPath'])}, name := {lean_string(r['name'])}, "
            f"value := {lean_string(r['value'])}, artifact := {lean_string(r['artifact'])} }},"
        )
    error_types = sorted(
        {r["name"] for r in types if "error-condition" in r["provides"]}
    )
    return f"""{HEADER}
import Generated.Oasis.Types

namespace {NAMESPACE}

/-- A declared choice: the symbolic values a restricted type or a field permits. -/
structure ChoiceDecl where
  ownerPath : String
  name : String
  value : String
  artifact : String
deriving Repr, DecidableEq

def choices : List ChoiceDecl := [
{chr(10).join(rows)}
]

/-- The types that provide the `error-condition` role. Every mandated refusal in
the specification names one of these families, so the mapping from a clause to
an error symbol is generated rather than remembered. -/
def errorConditionTypes : List String := {lean_list(error_types)}

/-- The error conditions declared by one family, ordered by symbol. -/
def errorConditionsOf (typeName : String) : List ChoiceDecl :=
  match (types.find? (fun entry => entry.name == typeName)).map (fun entry => entry.path) with
  | none => []
  | some path => choices.filter (fun entry => entry.ownerPath == path)

end {NAMESPACE}
"""


def render_provenance(digests: dict[str, str], counts: dict[str, int]) -> str:
    return (
        json.dumps(
            {
                "generator": "scripts/gen-oasis-lean.py",
                "artifacts": digests,
                "counts": counts,
                "note": "Counts are of records emitted into lean/Generated/Oasis; they are "
                "the declared surface, not a clause count (see ledger/clauses.json).",
            },
            indent=1,
            sort_keys=True,
        )
        + "\n"
    )


def generate(artifacts: Path, out: Path) -> dict[str, int]:
    records, digests = load(artifacts)

    constants = [r for r in records if r["kind"] == "constant"]
    types = [r for r in records if r["kind"] == "type"]
    descriptors = [r for r in records if r["kind"] == "descriptor"]
    fields = [r for r in records if r["kind"] == "field"]
    encodings = [r for r in records if r["kind"] == "encoding"]
    choices = [r for r in records if r["kind"] == "choice"]

    counts = {
        "constants": len(constants),
        "types": len(types),
        "descriptors": len(descriptors),
        "fields": len(fields),
        "encodings": len(encodings),
        "choices": len(choices),
    }

    modules = {
        "Constants.lean": render_constants(constants),
        "Types.lean": render_types(types, descriptors),
        "Fields.lean": render_fields(fields),
        "Encodings.lean": render_encodings(encodings),
        "Choices.lean": render_choices(choices, types),
        "provenance.json": render_provenance(digests, counts),
    }
    out.mkdir(parents=True, exist_ok=True)
    for name, content in modules.items():
        (out / name).write_text(content, encoding="utf-8")
    return counts


def generate_constants_only(records: list[dict]) -> list[dict]:
    return [r for r in records if r["kind"] == "constant"]


def main(argv: list[str]) -> int:
    root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--artifacts", default=str(root / "spec" / "oasis"))
    parser.add_argument("--out", default=str(root / "lean" / "Generated" / "Oasis"))
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate into a temporary directory and compare with the committed modules",
    )
    args = parser.parse_args(argv)

    if not args.check:
        counts = generate(Path(args.artifacts), Path(args.out))
        print(
            "generated declared surface: "
            + ", ".join(f"{key}={value}" for key, value in sorted(counts.items()))
        )
        print(f"wrote {args.out}")
        return 0

    with tempfile.TemporaryDirectory() as scratch:
        counts = generate(Path(args.artifacts), Path(scratch))
        committed = Path(args.out)
        problems = []
        for produced in sorted(Path(scratch).iterdir()):
            target = committed / produced.name
            if not target.is_file():
                problems.append(f"{produced.name}: missing from {committed}")
            elif produced.read_bytes() != target.read_bytes():
                problems.append(
                    f"{produced.name}: committed copy differs from a fresh generation "
                    "(regenerate with scripts/gen-oasis-lean.py)"
                )
        for problem in problems:
            print(f"  tables: {problem}")
        if problems:
            print("check FAILED: generated tables are not current")
            return 1
    print(
        "generated tables are current: "
        + ", ".join(f"{key}={value}" for key, value in sorted(counts.items()))
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
