#!/usr/bin/env python3
"""Generate a large value corpus for the reference implementation and the specification.

    scripts/gen-value-vectors.py [--out vectors/generated.ndjson]

The corpus has three families, and the *provenance of each expectation* is what
makes it worth having:

* **golden** — a value is encoded by this script's own encoder and the octets are
  asserted. The encoder is a third transcription of Part 1's encoding rules,
  written from the artifact's table and checked at import time against the
  worked examples the artifact publishes (the str8 example, the described-URL
  example and the composite `book` value). It is neither the Lean implementation
  nor the specification, so a vector it disagrees with is a real question.
* **reject** — malformed inputs: the reserved octets, the escape octets, every
  proper prefix of every golden vector (truncation), and size fields perturbed by
  one octet. Expectations here are properties of the grammar, not of an encoder.
* **property** — statements that need no oracle at all, over an exhaustive input
  domain: if a byte string decodes to a value, encoding that value must decode to
  the same value. Every input of one and two octets is emitted, so the domain is
  closed rather than sampled.

Nothing is generated by running either Lean artefact: a corpus produced by the
thing under test would only show that it equals itself.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import sys
from xml.etree import ElementTree

ROOT = pathlib.Path(__file__).resolve().parent.parent
ARTIFACT = ROOT / "spec" / "oasis" / "amqp-core-types-v1.0-os.xml"
WIDTHS_ANCHOR = "amqp-core-types-v1.0-os.xml#picture.5"
FIXED_ANCHOR = "amqp-core-types-v1.0-os.xml#picture.6"
ARRAY_ANCHOR = "amqp-core-types-v1.0-os.xml#picture.9"
COMPOUND_ANCHOR = "amqp-core-types-v1.0-os.xml#picture.8"
DESCRIBED_ANCHOR = "amqp-core-types-v1.0-os.xml#picture.2"
STRING_ANCHOR = "amqp-core-types-v1.0-os.xml#picture.1"
# Part 1's parity and ordering requirement for maps, as a clause of the ledger.
MAP_CLAUSE = "amqp:types/section:primitive-type-definitions/type:map.1"
# Part 1's array encoding clause: size, count, one element constructor, then count
# elements in that constructor's form. The count is bounded by the count field and by
# nothing in the data, which is why the zero-width element family is legal even when
# the element count exceeds the buffer (ledger/ambiguities/zero-width-array-count.json).
ENCODINGS_CLAUSE = "amqp-core-types-v1.0-os.xml#amqp:types/section:encodings.1"

# ---------------------------------------------------------------- the encoder


def be(n: int, width: int) -> bytes:
    return n.to_bytes(width, "big")


def enc_uint(n: int) -> bytes:
    if n == 0:
        return bytes([0x43])
    if n <= 0xFF:
        return bytes([0x52, n])
    if n <= 0xFFFFFFFF:
        return bytes([0x70]) + be(n, 4)
    raise ValueError("uint out of range")


def enc_ulong(n: int) -> bytes:
    if n == 0:
        return bytes([0x44])
    if n <= 0xFF:
        return bytes([0x53, n])
    if n <= 0xFFFFFFFFFFFFFFFF:
        return bytes([0x80]) + be(n, 8)
    raise ValueError("ulong out of range")


def enc_int(n: int) -> bytes:
    if -(2**31) <= n < 2**31:
        return bytes([0x71]) + be(n % 2**32, 4)
    raise ValueError("int out of range")


def enc_long(n: int) -> bytes:
    if -(2**63) <= n < 2**63:
        return bytes([0x81]) + be(n % 2**64, 8)
    raise ValueError("long out of range")


def enc_variable(narrow: int, wide: int, payload: bytes) -> bytes:
    if len(payload) <= 0xFF:
        return bytes([narrow, len(payload)]) + payload
    return bytes([wide]) + be(len(payload), 4) + payload


def fixed(label: str, payload_hex: str, width: int) -> bytes:
    """A fixed-width payload given as hex, checked against the declared width.

    The artifact's encoding table fixes how many octets each of the fixed-width
    encodings carries; a payload of the wrong length is a malformed vector, not a
    value, so it is refused here rather than written into the corpus.
    """
    payload = bytes.fromhex(payload_hex)
    if len(payload) != width:
        raise ValueError(f"{label} payload is {len(payload)} octets, the table declares {width}")
    return payload


def encode(value: dict) -> bytes:
    kind = value["type"]
    if kind == "null":
        return bytes([0x40])
    if kind == "boolean":
        return bytes([0x41 if value["value"] else 0x42])
    if kind == "ubyte":
        return bytes([0x50, value["value"]])
    if kind == "byte":
        return bytes([0x51, value["value"] % 256])
    if kind == "ushort":
        return bytes([0x60]) + be(value["value"], 2)
    if kind == "short":
        return bytes([0x61]) + be(value["value"] % 2**16, 2)
    if kind == "uint":
        return enc_uint(value["value"])
    if kind == "int":
        return enc_int(value["value"])
    if kind == "ulong":
        return enc_ulong(value["value"])
    if kind == "long":
        return enc_long(value["value"])
    if kind == "float":
        return bytes([0x72]) + fixed("float", value["hex"], 4)
    if kind == "double":
        return bytes([0x82]) + fixed("double", value["hex"], 8)
    if kind == "decimal32":
        return bytes([0x74]) + fixed("decimal32", value["hex"], 4)
    if kind == "decimal64":
        return bytes([0x84]) + fixed("decimal64", value["hex"], 8)
    if kind == "decimal128":
        return bytes([0x94]) + fixed("decimal128", value["hex"], 16)
    if kind == "char":
        codepoint = value["codepoint"]
        if not 0 <= codepoint <= 0x10FFFF:
            raise ValueError("char code point out of range")
        return bytes([0x73]) + be(codepoint, 4)
    if kind == "timestamp":
        # Two's complement milliseconds since the Unix epoch: a time before the
        # epoch is a wrapped octet string, not an error.
        return bytes([0x83]) + be(value["milliseconds"] % 2**64, 8)
    if kind == "uuid":
        return bytes([0x98]) + fixed("uuid", value["hex"], 16)
    if kind == "string":
        return enc_variable(0xA1, 0xB1, value["text"].encode())
    if kind == "symbol":
        return enc_variable(0xA3, 0xB3, value["text"].encode())
    if kind == "binary":
        return enc_variable(0xA0, 0xB0, bytes.fromhex(value["hex"]))
    if kind == "described":
        return bytes([0x00]) + encode(value["descriptor"]) + encode(value["value"])
    if kind == "list":
        body = b"".join(encode(item) for item in value["items"])
        if not value["items"]:
            return bytes([0x45])
        count = len(value["items"])
        # The size counts the octets after it: the count field (whose width
        # depends on the form) then the items.
        if 1 + len(body) <= 0xFF and count <= 0xFF:
            return bytes([0xC0, 1 + len(body), count]) + body
        return bytes([0xD0]) + be(4 + len(body), 4) + be(count, 4) + body
    if kind == "map":
        # Like list, but the count is the number of *items* — two per key/value
        # pair — and there is no map0 form, so the empty map is map8 with a zero
        # count. Part 1 requires an even item count; an odd one is not a map.
        pairs = value["pairs"]
        body = b"".join(encode(key) + encode(item) for key, item in pairs)
        count = 2 * len(pairs)
        if 1 + len(body) <= 0xFF and count <= 0xFF:
            return bytes([0xC1, 1 + len(body), count]) + body
        return bytes([0xD1]) + be(4 + len(body), 4) + be(count, 4) + body
    if kind == "array":
        ctor = int(value["constructor"], 16)
        elements = b"".join(element_data(ctor, item) for item in value["items"])
        count = len(value["items"])
        if 2 + len(elements) <= 0xFF and count <= 0xFF:
            return bytes([0xE0, 2 + len(elements), count, ctor]) + elements
        return (bytes([0xF0]) + be(5 + len(elements), 4) + be(count, 4)
                + bytes([ctor]) + elements)
    raise ValueError(f"unknown value type {kind!r}")


def compound_element_data(width: int, kind: str, count: int, body: bytes) -> bytes:
    """A compound element's data: the size and count fields the array's constructor
    fixes, then the body. A count or size the declared width cannot announce is a
    malformed vector, not a value, so it is refused here rather than written short."""
    size = width + len(body)
    if size >= 2 ** (8 * width) or count >= 2 ** (8 * width):
        raise ValueError(f"a {kind} element of width {width} cannot announce "
                         f"{count} item(s) in {len(body)} octet(s)")
    return be(size, width) + be(count, width) + body


def array_element_data(width: int, constructor: int, items: list[dict]) -> bytes:
    """An array element's data where the array's own element constructor is an array:
    its size and count in the outer array's declared width, its element constructor,
    then its elements. The inner array has no narrowest form of its own here — the
    outer constructor fixes it — which is what makes the forced width testable."""
    body = b"".join(element_data(constructor, item) for item in items)
    size = width + 1 + len(body)
    if size >= 2 ** (8 * width) or len(items) >= 2 ** (8 * width):
        raise ValueError(f"an array element of width {width} cannot announce "
                         f"{len(items)} element(s) in {len(body)} octet(s)")
    return be(size, width) + be(len(items), width) + bytes([constructor]) + body


def element_data(constructor: int, value: dict) -> bytes:
    """Array element data, in the array's declared constructor form.

    The array states its element constructor once, so each element's data is in that
    form and only that form: the width of a size, count or length field is the array's
    constructor's choice, never the element's own preference. Every constructor the
    table assigns is written here explicitly — there is no fallback to the element's own
    encoding, which would write a form the array does not declare — and a value the
    declared form cannot carry is refused rather than written in another form.
    """
    kind = value["type"]
    if constructor == 0x00:
        if kind != "described":
            raise ValueError(f"the descriptor prefix carries described values, not {kind}")
        return encode(value["descriptor"]) + encode(value["value"])
    if constructor in (0x40, 0x41, 0x42):
        return b""
    if constructor == 0x43:
        if kind != "uint" or value["value"] != 0:
            raise ValueError("a uint0 element carries the value 0")
        return b""
    if constructor == 0x44:
        if kind != "ulong" or value["value"] != 0:
            raise ValueError("a ulong0 element carries the value 0")
        return b""
    if constructor == 0x45:
        if kind != "list" or value["items"]:
            raise ValueError("a list0 element carries the empty list")
        return b""
    if constructor == 0x50:
        _expect(kind, "ubyte")
        return bytes([value["value"]])
    if constructor == 0x51:
        _expect(kind, "byte")
        return be(value["value"] % 2**8, 1)
    if constructor == 0x52:
        _expect(kind, "uint")
        return _octet(value["value"], 0xFF, "smalluint")
    if constructor == 0x53:
        _expect(kind, "ulong")
        return _octet(value["value"], 0xFF, "smallulong")
    if constructor == 0x54:
        _expect(kind, "int")
        return _signed_octet(value["value"], "smallint")
    if constructor == 0x55:
        _expect(kind, "long")
        return _signed_octet(value["value"], "smalllong")
    if constructor == 0x56:
        _expect(kind, "boolean")
        return bytes([1 if value["value"] else 0])
    if constructor == 0x60:
        _expect(kind, "ushort")
        return be(value["value"], 2)
    if constructor == 0x61:
        _expect(kind, "short")
        return be(value["value"] % 2**16, 2)
    if constructor == 0x70:
        _expect(kind, "uint")
        return be(value["value"], 4)
    if constructor == 0x71:
        _expect(kind, "int")
        return be(value["value"] % 2**32, 4)
    if constructor == 0x72:
        return fixed("float", value["hex"], 4)
    if constructor == 0x73:
        _expect(kind, "char")
        return be(value["codepoint"], 4)
    if constructor == 0x74:
        return fixed("decimal32", value["hex"], 4)
    if constructor == 0x80:
        _expect(kind, "ulong")
        return be(value["value"], 8)
    if constructor == 0x81:
        _expect(kind, "long")
        return be(value["value"] % 2**64, 8)
    if constructor == 0x82:
        return fixed("double", value["hex"], 8)
    if constructor == 0x83:
        _expect(kind, "timestamp")
        return be(value["milliseconds"] % 2**64, 8)
    if constructor == 0x84:
        return fixed("decimal64", value["hex"], 8)
    if constructor == 0x94:
        return fixed("decimal128", value["hex"], 16)
    if constructor == 0x98:
        return fixed("uuid", value["hex"], 16)
    if constructor == 0xA0:
        _expect(kind, "binary")
        return _length_prefixed(1, "vbin8", bytes.fromhex(value["hex"]))
    if constructor == 0xA1:
        _expect(kind, "string")
        return _length_prefixed(1, "str8", value["text"].encode())
    if constructor == 0xA3:
        _expect(kind, "symbol")
        return _length_prefixed(1, "sym8", value["text"].encode())
    if constructor == 0xB0:
        _expect(kind, "binary")
        return _length_prefixed(4, "vbin32", bytes.fromhex(value["hex"]))
    if constructor == 0xB1:
        _expect(kind, "string")
        return _length_prefixed(4, "str32", value["text"].encode())
    if constructor == 0xB3:
        _expect(kind, "symbol")
        return _length_prefixed(4, "sym32", value["text"].encode())
    if constructor in (0xC0, 0xD0):
        _expect(kind, "list")
        body = b"".join(encode(item) for item in value["items"])
        return compound_element_data(1 if constructor == 0xC0 else 4, "list",
                                     len(value["items"]), body)
    if constructor in (0xC1, 0xD1):
        _expect(kind, "map")
        body = b"".join(encode(key) + encode(item) for key, item in value["pairs"])
        return compound_element_data(1 if constructor == 0xC1 else 4, "map",
                                     2 * len(value["pairs"]), body)
    if constructor in (0xE0, 0xF0):
        _expect(kind, "array")
        inner = int(value["constructor"], 16)
        return array_element_data(1 if constructor == 0xE0 else 4, inner, value["items"])
    raise ValueError(f"element constructor {constructor:#04x} is not one the corpus writes")


def _expect(kind: str, wanted: str) -> None:
    if kind != wanted:
        raise ValueError(f"an element of this form carries {wanted} values, not {kind}")


def _octet(n: int, bound: int, label: str) -> bytes:
    if not 0 <= n <= bound:
        raise ValueError(f"a {label} element carries one octet and {n} does not fit")
    return bytes([n])


def _signed_octet(n: int, label: str) -> bytes:
    if not -128 <= n <= 127:
        raise ValueError(f"a {label} element carries one signed octet and {n} does not fit")
    return bytes([n % 2**8])


def _length_prefixed(width: int, label: str, payload: bytes) -> bytes:
    if len(payload) >= 2 ** (8 * width):
        raise ValueError(f"a {label} element carries {len(payload)} octet(s), which a "
                         f"{width}-octet length field cannot announce")
    return be(len(payload), width) + payload


# ------------------------------------------------- the artifact's own examples


def artifact_examples() -> list[tuple[str, dict, bytes]]:
    """The worked examples Part 1 publishes, as (name, value, octets)."""
    hello = "Hello Glorious Messaging World"
    url = "http://example.org/hello-world"
    title = "AMQP for & by Dummies"
    a1 = "Rob J. Godfrey"
    a2 = "Rafael H. Schloming"
    book = "example:book:list"
    book_value = {
        "type": "described",
        "descriptor": {"type": "symbol", "text": book},
        "value": {
            "type": "list",
            "items": [
                {"type": "string", "text": title},
                {"type": "array", "constructor": "a1",
                 "items": [{"type": "string", "text": a1}, {"type": "string", "text": a2}]},
                {"type": "null"},
            ],
        },
    }
    return [
        ("str8-hello", {"type": "string", "text": hello},
         bytes([0xA1, 0x1E]) + hello.encode()),
        ("described-url", {"type": "described", "descriptor": {"type": "string", "text": "URL"},
                           "value": {"type": "string", "text": url}},
         bytes([0x00, 0xA1, 0x03]) + b"URL" + bytes([0xA1, 0x1E]) + url.encode()),
        ("book-composite", book_value, bytes.fromhex(
            "00" "a311" + book.encode().hex() + "c04003" + "a115" + title.encode().hex()
            + "e02502" + "a10e" + a1.encode().hex() + "13" + a2.encode().hex() + "40")),
    ]


def self_check() -> None:
    """The generator must reproduce the artifact's examples, or it is not trusted."""
    for name, value, expected in artifact_examples():
        produced = encode(value)
        if produced != expected:
            raise SystemExit(
                f"gen-value-vectors: the encoder disagrees with the artifact's {name} example\n"
                f"  artifact: {expected.hex()}\n  produced: {produced.hex()}"
            )


# ------------------------------------------------------------------- families

DESCRIPTOR_SYMBOL = {"type": "symbol", "text": "amqp:example"}
DESCRIPTOR_ULONG = {"type": "ulong", "value": 0x00000000_00000001}


def golden() -> list[dict]:
    vectors: list[dict] = []

    def add(name: str, value: dict, anchor: str | list[str], note: str) -> None:
        clauses = [anchor] if isinstance(anchor, str) else list(anchor)
        vectors.append({
            "vector": f"gen-{name}", "kind": "encode", "clauses": clauses,
            "bytes": encode(value).hex(), "value": value, "note": note,
        })
        vectors.append({
            "vector": f"gen-{name}-decode", "kind": "decode", "clauses": clauses,
            "bytes": encode(value).hex(), "value": value, "canonical": True,
            "note": f"{note} (decoding direction)",
        })

    # Scalar boundaries. Every width is exercised on both sides of each boundary,
    # because that is where a narrowest-encoding rule and a size field disagree.
    for label, values, anchor in (
        ("ubyte", [0, 1, 127, 128, 255], WIDTHS_ANCHOR),
        ("byte", [-128, -1, 0, 1, 127], WIDTHS_ANCHOR),
        ("ushort", [0, 1, 255, 256, 32767, 65535], WIDTHS_ANCHOR),
        ("short", [-32768, -1, 0, 32767], WIDTHS_ANCHOR),
        ("uint", [0, 1, 254, 255, 256, 65535, 65536, 2**31 - 1, 2**32 - 1], WIDTHS_ANCHOR),
        ("int", [-(2**31), -1, 0, 2**31 - 1], WIDTHS_ANCHOR),
        ("ulong", [0, 1, 255, 256, 2**32 - 1, 2**32, 2**63, 2**64 - 1], WIDTHS_ANCHOR),
        ("long", [-(2**63), -1, 0, 2**63 - 1], WIDTHS_ANCHOR),
    ):
        for value in values:
            add(f"{label}-{value}", {"type": label, "value": value}, anchor,
                f"{label} value {value}, encoded in the narrowest form that carries it")

    add("null", {"type": "null"}, DESCRIBED_ANCHOR, "the null value")
    add("boolean-true", {"type": "boolean", "value": True}, WIDTHS_ANCHOR, "true")
    add("boolean-false", {"type": "boolean", "value": False}, WIDTHS_ANCHOR, "false")

    # Variable-width payloads: the 8-to-32-bit length boundary is where a writer
    # must switch form and a reader must not.
    for label, length in (("empty", 0), ("one", 1), ("short", 254), ("max8", 255),
                          ("over8", 256), ("large", 70000)):
        text = "x" * length
        add(f"string-{label}", {"type": "string", "text": text}, STRING_ANCHOR,
            f"a string of {length} octets")
        add(f"symbol-{label}", {"type": "symbol", "text": text}, STRING_ANCHOR,
            f"a symbol of {length} octets")
        add(f"binary-{label}", {"type": "binary", "hex": ("ab" * length)},
            STRING_ANCHOR, f"binary data of {length} octets")

    # Compounds: counts at the 8-bit boundary, sizes across it, nesting.
    for count in (0, 1, 2, 254, 255, 256, 300):
        items = [{"type": "ubyte", "value": i % 256} for i in range(count)]
        add(f"list-{count}", {"type": "list", "items": items}, COMPOUND_ANCHOR,
            f"a list of {count} booleans")
    for count in (0, 1, 2, 255, 256):
        items = [{"type": "string", "text": "e" * 40} for _ in range(count)]
        add(f"array-strings-{count}",
            {"type": "array", "constructor": "a1", "items": items}, ARRAY_ANCHOR,
            f"an array of {count} strings")
    add("array-null", {"type": "array", "constructor": "40",
                       "items": [{"type": "null"}, {"type": "null"}]}, ARRAY_ANCHOR,
        "an array of nulls, whose elements carry no data at all")

    # Zero-width element constructors: elements that carry no octets of their own, so
    # the buffer is smaller than the element count. Part 1 bounds the count by the
    # count field and by nothing in the data, so every one of these is a legal encoding
    # up to the declared element limit — in whichever form the count's width selects,
    # eight-bit up to 255 elements and thirty-two-bit beyond — and a reader must
    # materialise them rather than report truncation.
    for constructor, element in (("40", {"type": "null"}),
                                 ("41", {"type": "boolean", "value": True}),
                                 ("42", {"type": "boolean", "value": False})):
        for count in (0, 1, 2, 255, 256, 257):
            add(f"zero-width-{constructor}-{count}",
                {"type": "array", "constructor": constructor,
                 "items": [dict(element) for _ in range(count)]},
                ENCODINGS_CLAUSE,
                f"{count} zero-width {constructor} element(s) occupying no element data")
    add("list-nested",
        {"type": "list", "items": [
            {"type": "list", "items": [{"type": "uint", "value": 7}]},
            {"type": "array", "constructor": "70",
             "items": [{"type": "uint", "value": 1}, {"type": "uint", "value": 2}]},
            {"type": "described", "descriptor": DESCRIPTOR_SYMBOL, "value": {"type": "null"}},
        ]}, COMPOUND_ANCHOR, "a list containing a list, an array and a described value")
    add("described-symbol", {"type": "described", "descriptor": DESCRIPTOR_SYMBOL,
                             "value": {"type": "string", "text": "payload"}},
        DESCRIBED_ANCHOR, "a described value with a symbolic descriptor")
    add("described-numeric", {"type": "described", "descriptor": DESCRIPTOR_ULONG,
                              "value": {"type": "list", "items": []}},
        DESCRIBED_ANCHOR, "a described value with a numeric descriptor, wrapping the empty list")

    # The remaining fixed-width encodings. What the artifact's table fixes for
    # these is the framing — a format code and a declared number of octets — so the
    # float, double and decimal payloads are carried as raw hex rather than as JSON
    # numbers, which could not pin the octets a vector exists to pin down.
    for codepoint in (0, 65, 0x10FFFF):
        add(f"char-{codepoint:06x}", {"type": "char", "codepoint": codepoint},
            FIXED_ANCHOR,
            f"the code point U+{codepoint:04X}, UTF-32BE in four octets")
    for milliseconds in (0, 1, -(2**63), 2**63 - 1):
        add(f"timestamp-{milliseconds}", {"type": "timestamp", "milliseconds": milliseconds},
            FIXED_ANCHOR,
            f"{milliseconds} milliseconds since the Unix epoch, two's complement in eight octets")
    for label, payload in (("zero", "00" * 16),
                           ("rfc4122", "f81d4fae7dec11d0a76500a0c91e6bf6")):
        add(f"uuid-{label}", {"type": "uuid", "hex": payload}, FIXED_ANCHOR,
            f"a UUID in sixteen octets, the {label} pattern")
    for label, payload in (("positive-zero", "00000000"),
                           ("negative-zero", "80000000"),
                           ("one", "3f800000"),
                           ("min-subnormal", "00000001"),
                           ("max-finite", "7f7fffff"),
                           ("positive-infinity", "7f800000"),
                           ("negative-infinity", "ff800000")):
        add(f"float-{label}", {"type": "float", "hex": payload}, FIXED_ANCHOR,
            f"binary32 {label}: the sign, exponent and mantissa extremes in four octets")
    for label, payload in (("positive-zero", "0000000000000000"),
                           ("negative-zero", "8000000000000000"),
                           ("one", "3ff0000000000000"),
                           ("min-subnormal", "0000000000000001"),
                           ("max-finite", "7fefffffffffffff"),
                           ("positive-infinity", "7ff0000000000000"),
                           ("negative-infinity", "fff0000000000000")):
        add(f"double-{label}", {"type": "double", "hex": payload}, FIXED_ANCHOR,
            f"binary64 {label}: the sign, exponent and mantissa extremes in eight octets")
    for decimal, width in (("decimal32", 4), ("decimal64", 8), ("decimal128", 16)):
        for label, payload in (("zero", "00" * width), ("all-ones", "ff" * width)):
            add(f"{decimal}-{label}", {"type": decimal, "hex": payload}, FIXED_ANCHOR,
                f"{decimal} {label}: Binary Integer Decimal in {width} octets, carried as raw hex")

    # Maps. The count field is the number of items — two per pair — and there is no
    # map0 form, so the empty map is map8 with a zero item count. Keys are symbolic
    # and values mixed, and the pairs are given in wire order because Part 1 makes
    # that order semantically significant.
    def pair(index: int) -> list[dict]:
        values = ({"type": "null"}, {"type": "boolean", "value": True},
                  {"type": "ubyte", "value": index % 256},
                  {"type": "string", "text": f"v{index}"},
                  {"type": "uint", "value": index})
        return [{"type": "symbol", "text": f"k{index}"}, values[index % len(values)]]

    add("map-0", {"type": "map", "pairs": []}, MAP_CLAUSE,
        "the empty map: no map0 form exists, so map8 with a zero item count")
    add("map-1", {"type": "map", "pairs": [pair(0)]}, MAP_CLAUSE,
        "one symbolic key mapped to a null value, in wire order")
    for count in (127, 128, 255, 256):
        pairs = [pair(i) for i in range(count)]
        value = {"type": "map", "pairs": pairs}
        octets = encode(value)
        body = sum(len(encode(key)) + len(encode(item)) for key, item in pairs)
        add(f"map-{count}", value, MAP_CLAUSE,
            f"a map of {count} pairs, {2 * count} items in {len(octets)} octets: the item "
            f"count {'fits' if 2 * count <= 0xFF else 'does not fit'} the one-octet count "
            f"field and the body {'fits' if 1 + body <= 0xFF else 'does not fit'} the "
            f"one-octet size field, so {'map8' if octets[0] == 0xC1 else 'map32'} carries it")
    add("map-nested", {"type": "map", "pairs": [
        [{"type": "symbol", "text": "outer"},
         {"type": "map", "pairs": [[{"type": "symbol", "text": "inner"},
                                    {"type": "uint", "value": 7}]]}],
        [{"type": "symbol", "text": "tail"}, {"type": "null"}],
    ]}, MAP_CLAUSE, "a map with a map as one of its values")
    return vectors


def rejects(golden_vectors: list[dict]) -> list[dict]:
    vectors: list[dict] = []

    # Every octet below the format-code ranges, and the twelve escape octets.
    for code in range(0x01, 0x40):
        vectors.append({
            "vector": f"gen-reserved-{code:02x}", "kind": "reject",
            "clauses": [WIDTHS_ANCHOR], "bytes": f"{code:02x}",
            "expectError": {"condition": "amqp:decode-error", "endpoint": "connection"},
            "note": f"0x{code:02X} lies below every format-code range",
        })
    for code in (0x4F, 0x5F, 0x6F, 0x7F, 0x8F, 0x9F, 0xAF, 0xBF, 0xCF, 0xDF, 0xEF, 0xFF):
        vectors.append({
            "vector": f"gen-escape-{code:02x}", "kind": "reject",
            "clauses": ["amqp-core-types-v1.0-os.xml#picture.3"], "bytes": f"{code:02x}00",
            "expectError": {"condition": "amqp:decode-error", "endpoint": "connection"},
            "note": f"0x{code:02X} is an escape octet reserved for future formats",
        })

    # Part 1: a map's items are alternating keys and values, so the count must be
    # even. The size field here is exactly right, leaving the parity the only
    # thing wrong with the input.
    odd = b"".join(encode(item) for item in (
        {"type": "symbol", "text": "a"}, {"type": "uint", "value": 0}, {"type": "null"}))
    vectors.append({
        "vector": "gen-map-odd-items", "kind": "reject", "clauses": [MAP_CLAUSE],
        "bytes": (bytes([0xC1, 1 + len(odd), 3]) + odd).hex(),
        "expectError": {"condition": "amqp:decode-error", "endpoint": "connection"},
        "note": "a map declaring three items: keys and values must come in pairs, "
                "so an odd item count is not a map",
    })

    # The declared element limit on the zero-width family, and its size control. A ten
    # octet buffer can declare billions of elements, so what bounds an array of them is
    # the declared limit — named, so that it is never mistaken for truncation — and the
    # size field is still checked where it lies.
    vectors.append({
        "vector": "gen-zero-width-40-over-limit", "kind": "reject",
        "clauses": [ENCODINGS_CLAUSE],
        "bytes": (bytes([0xF0]) + be(5, 4) + be(65537, 4) + bytes([0x40])).hex(),
        "expectError": {"condition": "amqp:decode-error", "endpoint": "connection",
                        "reason": "limit"},
        "note": "65537 zero-width elements: refused by the declared element limit, not "
                "by truncation, because a count is not an octet count",
    })
    vectors.append({
        "vector": "gen-zero-width-40-bad-size", "kind": "reject",
        "clauses": [ENCODINGS_CLAUSE],
        "bytes": (bytes([0xE0, 0x03, 0x0A, 0x40])).hex(),
        "expectError": {"condition": "amqp:decode-error", "endpoint": "connection",
                        "reason": "sizeMismatch"},
        "note": "ten zero-width elements with the size field raised by one: the reading "
                "measures two octets where three are declared, which is a size mismatch "
                "rather than a limit",
    })

    # Every proper prefix of every golden encoding must be rejected as truncated.
    for entry in golden_vectors:
        octets = bytes.fromhex(entry["bytes"])
        if len(octets) < 2 or len(octets) > 40:
            continue                      # keep the sweep to short vectors
        for cut in range(1, len(octets)):
            vectors.append({
                "vector": f"trunc-{entry['vector']}-{cut}", "kind": "reject",
                "clauses": entry["clauses"],
                "bytes": octets[:cut].hex(),
                "expectError": {"condition": "amqp:decode-error", "endpoint": "connection"},
                "note": f"the first {cut} of {len(octets)} octets of {entry['vector']}",
            })

    # Size fields perturbed by one octet, for the compound encodings. A reader that
    # trusts the declared size instead of measuring its own window accepts a map
    # whose size field is short, so this is the control that makes the check bite.
    for entry in golden_vectors:
        octets = bytearray.fromhex(entry["bytes"])
        value = entry.get("value", {})
        if value.get("type") not in ("list", "map") or len(octets) < 3:
            continue
        if octets[0] not in (0xC0, 0xD0, 0xC1, 0xD1):
            continue
        for delta in (-1, 1):
            # The vector id must satisfy the schema's `^[a-z0-9][a-z0-9._-]*$`, so
            # the sign is spelled out rather than written as `+`/`-`.
            direction = "minus1" if delta < 0 else "plus1"
            if octets[0] in (0xC0, 0xC1):
                perturbed = bytearray(octets)
                perturbed[1] = (perturbed[1] + delta) % 256
            else:
                size = int.from_bytes(octets[1:5], "big") + delta
                perturbed = bytearray(octets[:1]) + size.to_bytes(4, "big") + octets[5:]
            vectors.append({
                "vector": f"size-{direction}-{entry['vector']}", "kind": "reject",
                "clauses": entry["clauses"], "bytes": bytes(perturbed).hex(),
                "expectError": {"condition": "amqp:decode-error", "endpoint": "connection"},
                "note": f"{entry['vector']} with its size field moved by {delta}",
            })
    return vectors


def properties() -> list[dict]:
    """Exhaustive short inputs, asserting a law that needs no oracle.

    If a byte string decodes to a value, encoding that value must decode to the
    same value. Inputs that fail to decode make no claim, so the whole space of
    one- and two-octet inputs can be swept without an expected answer for each.
    """
    vectors: list[dict] = []
    for first in range(256):
        vectors.append({
            "vector": f"prop-{first:02x}", "kind": "property",
            "property": "decode-stable", "clauses": [WIDTHS_ANCHOR],
            "bytes": f"{first:02x}",
        })
    for first in range(256):
        for second in range(256):
            vectors.append({
                "vector": f"prop-{first:02x}{second:02x}", "kind": "property",
                "property": "decode-stable", "clauses": [WIDTHS_ANCHOR],
                "bytes": f"{first:02x}{second:02x}",
            })
    return vectors


# --------------------------------------------------------------- frame vectors
#
# The frame layer's layout is prose and ASCII art in the framing section rather than a
# machine-readable declaration, so this transcribes it exactly as the two frame layers
# do, and cites the same clauses. Everything else is *read* from the declared surface:
# which types are performatives, which fields each one carries, which of those are
# mandatory, what their defaults say, and what the artifact defines MIN-MAX-FRAME-SIZE
# to be. Nothing here is a second hand-written list of any of that.

FRAMING_CLAUSE = "amqp-core-transport-v1.0-os.xml#amqp:transport/section:framing.1"
PERFORMATIVE_CLAUSE = "amqp-core-transport-v1.0-os.xml#amqp:transport/section:framing.3"
SASL_CLAUSE = "amqp-core-security-v1.0-os.xml#amqp:security/section:sasl.1"

FRAME_HEADER = 8      # the layout: a fixed eight-octet frame header
FRAME_WORD = 4        # DOFF counts four-octet words
FRAME_MIN_DOFF = 2    # with an eight-octet header the body cannot start earlier
AMQP_FRAME = 0x00
SASL_FRAME = 0x01

# The element constructor an array field's elements are written under: the fixed forms
# the fields of these performatives name, since an array's elements are written in the
# array's declared form. (The element-constructor family below covers the rest of the
# table, including the compound and array categories.)
ARRAY_CONSTRUCTOR = {"symbol": "a3", "string": "a1", "binary": "a0",
                     "ubyte": "50", "ushort": "60", "uint": "70", "ulong": "80"}


def declared_types() -> dict[str, ElementTree.Element]:
    """Every declared type across the pinned artifacts, by name.

    Part 2 and Part 5 declare the performatives and Part 1 declares most of the types
    their fields name, while a restricted type may be declared in one part and used in
    another, so the whole declared surface is read rather than a single artifact.
    """
    types: dict[str, ElementTree.Element] = {}
    for path in sorted((ROOT / "spec" / "oasis").glob("amqp-core-*-v1.0-os.xml")):
        for element in ElementTree.parse(path).getroot().iter("type"):
            if element.get("name") and element.get("class"):
                types.setdefault(element.get("name"), element)
    return types


def defined_constant(name: str) -> str:
    """The value of a `<definition>` the artifact's text names, so a constant a vector
    asserts about is read rather than copied."""
    for path in sorted((ROOT / "spec" / "oasis").glob("amqp-core-*-v1.0-os.xml")):
        for element in ElementTree.parse(path).getroot().iter("definition"):
            if element.get("name") == name:
                return element.get("value")
    raise SystemExit(f"gen-value-vectors: the artifacts define no constant {name!r}")


def type_chain(types: dict[str, ElementTree.Element], name: str) -> list[ElementTree.Element]:
    """A declared type and the restricted types it is defined over, in order."""
    chain: list[ElementTree.Element] = []
    current = types.get(name)
    while current is not None:
        chain.append(current)
        if current.get("class") != "restricted":
            break
        current = types.get(current.get("source"))
    if not chain or chain[-1].get("class") != "primitive":
        raise SystemExit(f"gen-value-vectors: {name!r} does not resolve to a primitive type")
    return chain


def primitive_name(types: dict[str, ElementTree.Element], name: str) -> str:
    return type_chain(types, name)[-1].get("name")


def sample_value(types: dict[str, ElementTree.Element], declared: str) -> dict:
    """A value of the declared type, for a field that must be present and carries no
    default. Only the primitives the performatives' mandatory fields actually reach are
    given a sample: a type with no sample is a generator gap, and says so rather than
    guessing at an encoding."""
    primitive = primitive_name(types, declared)
    if primitive == "string":
        return {"type": "string", "text": "v"}
    if primitive == "symbol":
        return {"type": "symbol", "text": "PLAIN"}
    if primitive == "binary":
        return {"type": "binary", "hex": "00"}
    if primitive == "boolean":
        return {"type": "boolean", "value": True}
    if primitive in ("ubyte", "ushort", "uint", "ulong", "byte", "short", "int", "long"):
        return {"type": primitive, "value": 0}
    if primitive == "timestamp":
        return {"type": "timestamp", "milliseconds": 0}
    if primitive == "char":
        return {"type": "char", "codepoint": 65}
    if primitive == "uuid":
        return {"type": "uuid", "hex": "00" * 16}
    raise SystemExit(f"gen-value-vectors: no sample value for a {primitive!r} field")


def default_value(types: dict[str, ElementTree.Element], declared: str, text: str) -> dict:
    """The artifact's `default` attribute read as a value of the field's declared type.

    The attribute is untyped text — numerals, booleans and choice names in one field —
    so reading it is a transcription rule of its own, and this is the one place it
    lives. A numeral becomes a value of the primitive the type resolves to, `true` and
    `false` become booleans, and anything else must name one of the type's declared
    choice values, which the artifact gives a numeral for.
    """
    primitive = primitive_name(types, declared)
    if text in ("true", "false"):
        if primitive != "boolean":
            raise SystemExit(f"gen-value-vectors: {declared} default {text!r} is not a boolean")
        return {"type": "boolean", "value": text == "true"}
    try:
        number: int | None = int(text)
    except ValueError:
        number = None
    if number is None:
        for element in type_chain(types, declared):
            for child in element:
                if child.tag == "choice" and child.get("name") == text:
                    number = int(child.get("value"))
    if number is None:
        raise SystemExit(f"gen-value-vectors: {declared} default {text!r} is neither a "
                         f"numeral, a boolean nor a declared choice name")
    if primitive not in ("ubyte", "ushort", "uint", "ulong", "byte", "short", "int", "long"):
        raise SystemExit(f"gen-value-vectors: {declared} default {text!r} is a numeral while "
                         f"the type resolves to {primitive}")
    return {"type": primitive, "value": number}


def field_value(types: dict[str, ElementTree.Element], field: ElementTree.Element) -> dict | None:
    """A field's value: its declared default where it has one, a sample where it is
    mandatory, and null where it is neither — and the trailing nulls are then dropped
    from the end of the field list, which is what the trailing-null rule allows."""
    declared = field.get("type")
    default = field.get("default")
    if default is not None:
        return default_value(types, declared, default)
    if field.get("mandatory") == "true":
        if field.get("multiple") == "true":
            primitive = primitive_name(types, declared)
            if primitive not in ARRAY_CONSTRUCTOR:
                raise SystemExit(f"gen-value-vectors: no array constructor for {primitive!r}")
            return {"type": "array", "constructor": ARRAY_CONSTRUCTOR[primitive],
                    "items": [sample_value(types, declared)]}
        return sample_value(types, declared)
    return None


def performative_value(types: dict[str, ElementTree.Element], element: ElementTree.Element) -> dict:
    """One performative as a described value: its descriptor, and its fields in wire
    order."""
    descriptor = next(element.iter("descriptor"))
    code = int(descriptor.get("code").split(":")[1], 16)
    fields = list(element.iter("field"))
    last = 0
    for index, field in enumerate(fields):
        if field.get("default") is not None or field.get("mandatory") == "true":
            last = index + 1
    items = []
    for field in fields[:last]:
        value = field_value(types, field)
        items.append(value if value is not None else {"type": "null"})
    return {"type": "described", "descriptor": {"type": "ulong", "value": code},
            "value": {"type": "list", "items": items}}


def performatives(types: dict[str, ElementTree.Element]) -> list[tuple[str, int, int]]:
    """Every performative the artifacts give a frame role, as (name, descriptor code,
    frame type octet). The role is the artifact's own `provides`, not a list here."""
    found: list[tuple[str, int, int]] = []
    for artifact, provides, frame_type in (
            ("amqp-core-transport-v1.0-os.xml", "frame", AMQP_FRAME),
            ("amqp-core-security-v1.0-os.xml", "sasl-frame", SASL_FRAME)):
        root = ElementTree.parse(ROOT / "spec" / "oasis" / artifact).getroot()
        for element in root.iter("type"):
            if provides in (element.get("provides") or "").split():
                descriptor = next(element.iter("descriptor"))
                code = int(descriptor.get("code").split(":")[1], 16)
                found.append((element.get("name"), code, frame_type))
    return found


def frame_octets(frame_type: int, doff: int, body: bytes, payload: bytes = b"",
                 extended: bytes = b"", channel: int = 0) -> bytes:
    """The frame a body is carried in, with SIZE computed from the octets exactly as the
    layout requires: header, extended header and frame body."""
    size = FRAME_HEADER + len(extended) + len(body) + len(payload)
    return be(size, 4) + bytes([doff, frame_type]) + be(channel, 2) + extended + body + payload


def frame_pair(vectors: list[dict], name: str, frame_type: int, doff: int, body: dict,
               payload: bytes = b"", extended: bytes = b"",
               clauses: list[str] | None = None, note: str = "") -> None:
    """One frame as both directions of the corpus: its octets decode to it, and it
    encodes to those octets."""
    clause_list = clauses if clauses is not None else [FRAMING_CLAUSE, PERFORMATIVE_CLAUSE]
    body_bytes = encode(body)
    octets = frame_octets(frame_type, doff, body_bytes, payload, extended)
    frame: dict = {"size": len(octets), "doff": doff, "type": f"{frame_type:02x}",
                   "channel": 0, "body": [body]}
    if extended:
        frame["extended"] = extended.hex()
    if payload:
        frame["payload"] = payload.hex()
    vectors.append({"vector": f"gen-frame-{name}", "kind": "frame-decode",
                    "clauses": clause_list, "bytes": octets.hex(), "frame": frame,
                    "note": note})
    vectors.append({"vector": f"gen-frame-{name}-encode", "kind": "frame-encode",
                    "clauses": clause_list, "bytes": octets.hex(), "frame": frame,
                    "note": f"{note}; the write direction, where SIZE is computed rather "
                            f"than carried"})


def frame_reject(vectors: list[dict], name: str, octets: bytes, reason: str, note: str,
                 clauses: list[str] | None = None) -> None:
    vectors.append({
        "vector": f"gen-frame-{name}", "kind": "frame-reject",
        "clauses": clauses if clauses is not None else [FRAMING_CLAUSE],
        "bytes": octets.hex(),
        "expectError": {"condition": "amqp:connection:framing-error",
                        "endpoint": "connection", "reason": reason},
        "note": note,
    })


def frame_corpus() -> list[dict]:
    """The frame corpus: every performative in both directions and in the frame type its
    role gives it, the size and DOFF arithmetic at the boundaries, the layout's malformed
    arithmetic, and the mutation controls that require a body to be read rather than
    skipped."""
    types = declared_types()
    vectors: list[dict] = []
    bodies: dict[str, dict] = {}
    for name, _, frame_type in performatives(types):
        bodies[name] = performative_value(types, types[name])
        clauses = [FRAMING_CLAUSE, PERFORMATIVE_CLAUSE]
        if frame_type == SASL_FRAME:
            clauses.append(SASL_CLAUSE)
        role = "SASL" if frame_type == SASL_FRAME else "AMQP"
        frame_pair(vectors, f"performative-{name}", frame_type, FRAME_MIN_DOFF, bodies[name],
                   clauses=clauses,
                   note=f"the {name} performative in a {role} frame, carrying every field "
                        f"the declared surface makes mandatory or gives a default, with the "
                        f"trailing nulls dropped")

    open_body = bodies["open"]
    open_octets = len(encode(open_body))
    limit = int(defined_constant("MIN-MAX-FRAME-SIZE"))
    for label, total in (("at-min-max-frame-size", limit),
                         ("one-over-min-max-frame-size", limit + 1)):
        frame_pair(vectors, f"size-{label}", AMQP_FRAME, FRAME_MIN_DOFF, open_body,
                   payload=b"\x2a" * (total - FRAME_HEADER - open_octets),
                   note=f"a frame of exactly {total} octets: MIN-MAX-FRAME-SIZE is "
                        f"{limit}, the bound the artifact defines and this counts to")
    frame_pair(vectors, "doff-three", AMQP_FRAME, 3, open_body,
               extended=b"\x00" * (3 * FRAME_WORD - FRAME_HEADER),
               note="DOFF of three: four octets of extended header, which an AMQP frame "
                    "ignores rather than refuses")
    largest = (FRAME_HEADER + (3 * FRAME_WORD - FRAME_HEADER) + open_octets) // FRAME_WORD
    frame_pair(vectors, "doff-largest-for-body", AMQP_FRAME, largest, open_body,
               extended=b"\x00" * (largest * FRAME_WORD - FRAME_HEADER),
               note=f"DOFF of {largest}, the largest that still leaves the body inside SIZE "
                    f"for this frame, with the body beginning at the extended header's end")

    good = frame_octets(AMQP_FRAME, FRAME_MIN_DOFF, encode(open_body))
    below = bytearray(good)
    below[3] = FRAME_HEADER + open_octets - 2
    frame_reject(vectors, "size-below-body", bytes(below), "sizeMismatch",
                 "SIZE claims fewer octets than the performative needs")
    inside = bytearray(good)
    inside[4] = FRAME_MIN_DOFF - 1
    frame_reject(vectors, "doff-below-minimum", bytes(inside), "sizeMismatch",
                 "DOFF of one puts the body inside the eight-octet header")
    beyond = bytearray(good)
    beyond[4] = FRAME_MIN_DOFF + 2
    frame_reject(vectors, "doff-beyond-size", bytes(beyond), "sizeMismatch",
                 "DOFF puts the body past the octets SIZE declares")
    unassigned_type = bytearray(good)
    unassigned_type[5] = 0x02
    frame_reject(vectors, "type-unknown", bytes(unassigned_type), "unsupported",
                 "TYPE 0x02 is not a frame type this specification assigns")
    frame_reject(vectors, "header-truncated", bytes(good[:FRAME_HEADER - 1]), "truncated",
                 "seven octets where the header alone needs eight")

    # The mutation controls: a frame layer that skipped the body rather than reading it
    # would accept both of these.
    open_bytes = encode(open_body)
    frame_reject(vectors, "descriptor-unassigned",
                 frame_octets(AMQP_FRAME, FRAME_MIN_DOFF, bytes([0x01]) + open_bytes[1:]),
                 "unassigned",
                 "the performative's descriptor octet replaced by 0x01, which is below "
                 "every format-code range, so refusing this needs the body to be read")
    frame_reject(vectors, "body-not-described",
                 frame_octets(AMQP_FRAME, FRAME_MIN_DOFF, bytes([0x40]) + open_bytes[1:]),
                 "malformed",
                 "the body's first octet replaced by null: still a value, but not the "
                 "described type the layout requires a performative to be")
    return vectors


# ---------------------------------------------------- element-constructor vectors
#
# A family of its own, next to the zero-width one above and not inside it: that family
# is about a count the buffer cannot bound, this one is about which element forms are
# read at all. Part 1 makes an array's element constructor a *constructor* — a
# `format-code` or the descriptor prefix — and its `format-code` production admits all
# four categories, so a scalar, a compound and an array are each legal element data.

# Every element constructor a reader reads, with the note each vector carries. The
# ones the corpus already had vectors for (null, the booleans, ubyte, ushort, uint,
# ulong, byte, short, int, long, float, double and the decimals, char, timestamp, uuid,
# binary, string, symbol) appear here too, because an array's *declared* form decides
# how its elements are written and a construction the earlier families never exercised
# is written here for the first time.
ELEMENT_FORMS = [
    (0x00, "described", "the descriptor prefix stands as the element constructor, so "
                        "each element carries its own descriptor and value"),
    (0x43, "uint0", "the uint zero form, whose elements carry no octets at all"),
    (0x44, "ulong0", "the ulong zero form, whose elements carry no octets at all"),
    (0x45, "list0", "the empty-list form, whose elements carry no octets at all"),
    (0x52, "smalluint", "a one-octet unsigned element"),
    (0x53, "smallulong", "a one-octet unsigned element"),
    (0x56, "boolean", "one octet, false for 0x00 and true for anything else"),
    (0x61, "short", "two octets of two's complement"),
    (0x71, "int", "four octets of two's complement"),
    (0x81, "long", "eight octets of two's complement"),
    (0xB0, "vbin32", "a four-octet length prefix, then the payload"),
    (0xB1, "str32", "a four-octet length prefix, then the payload"),
    (0xB3, "sym32", "a four-octet length prefix, then the payload"),
    (0xC0, "list8", "a compound element: its own one-octet size and count, then its items"),
    (0xC1, "map8", "a compound element: its own one-octet size and count, then its pairs"),
    (0xD0, "list32", "a compound element in its four-octet form"),
    (0xD1, "map32", "a compound element in its four-octet form"),
    (0xE0, "array8", "an array element: its own one-octet size and count, its element "
                     "constructor, then its elements"),
    (0xF0, "array32", "an array element in its four-octet form"),
]


def element_value(constructor: int, index: int) -> dict:
    """The `index`-th element an array of this declared constructor carries."""
    if constructor == 0x00:
        return {"type": "described",
                "descriptor": {"type": "symbol", "text": "element"},
                "value": {"type": "ubyte", "value": index % 256}}
    if constructor == 0x43:
        return {"type": "uint", "value": 0}
    if constructor == 0x44:
        return {"type": "ulong", "value": 0}
    if constructor == 0x45:
        return {"type": "list", "items": []}
    if constructor == 0x52:
        return {"type": "uint", "value": index % 256}
    if constructor == 0x53:
        return {"type": "ulong", "value": index % 256}
    if constructor == 0x56:
        return {"type": "boolean", "value": index % 2 == 0}
    if constructor == 0x61:
        return {"type": "short", "value": index - 128}
    if constructor == 0x71:
        return {"type": "int", "value": index - 128}
    if constructor == 0x81:
        return {"type": "long", "value": index - 128}
    if constructor == 0xB0:
        return {"type": "binary", "hex": "ab" * (1 + index % 2)}
    if constructor == 0xB1:
        return {"type": "string", "text": "s" * (1 + index % 2)}
    if constructor == 0xB3:
        return {"type": "symbol", "text": "k" * (1 + index % 2)}
    if constructor in (0xC0, 0xD0):
        return {"type": "list", "items": [{"type": "ubyte", "value": index % 256}]}
    if constructor in (0xC1, 0xD1):
        return {"type": "map",
                "pairs": [[{"type": "symbol", "text": "k"},
                           {"type": "ubyte", "value": index % 256}]]}
    if constructor in (0xE0, 0xF0):
        return {"type": "array", "constructor": "50",
                "items": [{"type": "ubyte", "value": index % 256}]}
    raise ValueError(f"the corpus writes no element of constructor {constructor:#04x}")


def element_arrays() -> list[dict]:
    """Arrays of every element constructor, in both directions.

    Counts are either side of the one-octet count boundary — 0, 1, 255 and 256
    elements — so the array's own count field, and for a container element the
    element's own size and count fields, are exercised where they switch width.
    """
    vectors: list[dict] = []

    def add(name: str, value: dict, note: str) -> None:
        octets = encode(value)
        vectors.append({
            "vector": f"gen-element-{name}", "kind": "encode",
            "clauses": [ENCODINGS_CLAUSE], "bytes": octets.hex(), "value": value,
            "note": note,
        })
        vectors.append({
            "vector": f"gen-element-{name}-decode", "kind": "decode",
            "clauses": [ENCODINGS_CLAUSE], "bytes": octets.hex(), "value": value,
            "canonical": True, "note": f"{note} (decoding direction)",
        })

    for constructor, label, note in ELEMENT_FORMS:
        for count in (0, 1, 255, 256):
            value = {"type": "array", "constructor": f"{constructor:02x}",
                     "items": [element_value(constructor, i) for i in range(count)]}
            octets = encode(value)
            add(f"array-{label}-{count}", value,
                f"an array of {count} element(s) whose declared constructor is {label}: "
                f"{note}. The array's count field is "
                f"{'one octet' if count <= 0xFF else 'four octets'} and its element count "
                f"{'fits' if count <= 0xFF else 'does not fit'} a one-octet count field, so "
                f"{'array8' if octets[0] == 0xE0 else 'array32'} carries it")

    # The array category, nested. An inner array has no narrowest form of its own when it
    # is an element: the outer array's constructor fixes the width of the inner size and
    # count fields, so these vectors pin the forced width as well as the nesting.
    def inner(constructor: int, items: list[dict]) -> dict:
        return {"type": "array", "constructor": f"{constructor:02x}", "items": items}

    add("array8-of-array8", inner(0xE0, [
        inner(0x50, [{"type": "ubyte", "value": 1}, {"type": "ubyte", "value": 2}]),
        inner(0x50, [{"type": "ubyte", "value": 3}]),
    ]), "an array whose element constructor is array8, holding two inner arrays: each "
        "inner array is written in eight-bit form because the outer constructor declares "
        "it, not because the inner array would choose it")
    for count in (255, 256):
        add(f"array32-of-array32-inner-{count}", inner(0xF0, [
            inner(0x40, [{"type": "null"}] * count),
        ]), f"an array of arrays in thirty-two-bit form, whose inner array declares "
            f"{count} zero-width elements: the inner count lies "
            f"{'at' if count == 256 else 'below'} the one-octet boundary and the inner "
            f"array is written in the outer constructor's four-octet form regardless")
    add("array8-of-array-compound-inner", inner(0xE0, [
        inner(0xC0, [{"type": "list", "items": [{"type": "ubyte", "value": 1}]},
                     {"type": "list", "items": []}]),
    ]), "an array of arrays whose inner element constructor is itself a compound: the "
        "inner array's elements are list8 bodies, each with its own size and count")
    add("array8-of-list8-of-array8", inner(0xC0, [
        {"type": "list", "items": [inner(0x40, [{"type": "null"}, {"type": "null"}])]},
        {"type": "list", "items": []},
    ]), "an array of compound elements nested two deep: an array whose element "
        "constructor is list8, one of whose lists holds an array8 of nulls")
    return vectors


def element_rejects() -> list[dict]:
    """The refusals the element forms now admit.

    Each names the reason class both artefacts must report, because a rejection that
    merely fails would let a truncation stand in for a size disagreement.
    """
    vectors: list[dict] = []

    def reject(name: str, octets: bytes, reason: str, note: str) -> None:
        vectors.append({
            "vector": f"gen-element-{name}", "kind": "reject",
            "clauses": [ENCODINGS_CLAUSE], "bytes": octets.hex(),
            "expectError": {"condition": "amqp:decode-error", "endpoint": "connection",
                            "reason": reason},
            "note": note,
        })

    # A compound element whose size disagrees with its contents: the element's own size
    # octet is raised by one, leaving the array's size exactly right, so the element's
    # check is what fires rather than the array's.
    listing = encode({"type": "list", "items": [{"type": "ubyte", "value": 7}]})
    element = bytes([len(listing) + 1, 1]) + listing
    array = bytes([0xE0, 2 + len(element), 1, 0xC0]) + element
    raised = bytearray(array)
    raised[4] = raised[4] + 1
    reject("list8-element-bad-size", bytes(raised), "sizeMismatch",
           "a list8 element whose size octet is one higher than its count and items "
           "measure: the element's own check refuses it")

    # A nested array element whose size disagrees, one level further in.
    nested = bytes([0xE0, 5, 1, 0xE0, 2, 1, 0x40])
    raised = bytearray(nested)
    raised[4] = 3
    reject("array8-element-bad-size", bytes(raised), "sizeMismatch",
           "an array8 element inside an array8, its inner size octet raised by one: the "
           "inner array's size check refuses it before the outer one is reached")

    # A variable-width element whose length prefix runs past the array's size: the
    # element declares eight payload octets where the array's size announces two, and the
    # six extra octets are present in the buffer so what fires is the array's size
    # measurement rather than a truncation.
    # The payload is ASCII, so the element's own payload check has nothing to say and the
    # array's size measurement is what fires.
    overrun = bytes([0xE0, 8, 1, 0xB1]) + be(8, 4) + b"ab" + b"cd" * 6
    reject("str32-element-length-over-array-size", overrun, "sizeMismatch",
           "a str32 element declaring eight payload octets where the array's size "
           "announces two, with the octets present in the buffer: the array measures "
           "more than its size field declares")

    # An element constructor that is not a constructor the grammar assigns: the escape
    # octet 0x4F, and 0x46, a format code the table leaves unassigned inside the
    # zero-data range. Both are refused before any element is read, so an array that
    # declares no elements at all is refused too — a reader that only looked at the
    # elements would accept the empty one.
    for label, octet in (("escape-4f", 0x4F), ("unassigned-46", 0x46)):
        for count in (0, 1):
            octets = bytes([0xE0, 2 + count, count, octet]) + b"\x00" * count
            reject(f"constructor-{label}-{count}-elements", octets, "unassigned",
                   f"an array of {count} element(s) whose element constructor is "
                   f"0x{octet:02X}, which no format code assigns: refused for the "
                   f"constructor, whether or not elements follow")
    return vectors


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", default=str(ROOT / "vectors" / "generated.ndjson"))
    parser.add_argument("--limit-properties", type=int, default=None,
                        help="emit only the first N property vectors, for a quick pass")
    parser.add_argument("--frames", default=None, metavar="PATH",
                        help="also emit the frame corpus (every performative in both "
                             "directions, the size and DOFF boundaries, the layout's "
                             "malformed arithmetic and the mutation controls) to PATH")
    args = parser.parse_args(argv)

    self_check()
    gold = golden() + element_arrays()
    corpus = gold + rejects(gold) + element_rejects() + properties()
    if args.limit_properties is not None:
        props = [v for v in corpus if v["kind"] == "property"]
        corpus = [v for v in corpus if v["kind"] != "property"] + props[:args.limit_properties]

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(json.dumps(v, sort_keys=True) for v in corpus) + "\n",
                   encoding="utf-8")
    counts: dict[str, int] = {}
    for vector in corpus:
        counts[vector["kind"]] = counts.get(vector["kind"], 0) + 1
    digest = hashlib.sha256(out.read_bytes()).hexdigest()
    print(f"generated {len(corpus)} vectors into {out}")
    print("  kinds: " + ", ".join(f"{k}={v}" for k, v in sorted(counts.items())))
    print(f"  artifact: {hashlib.sha256(ARTIFACT.read_bytes()).hexdigest()[:16]}… "
          f"(the table the encoder was read from)")
    print(f"  sha256: {digest}")

    if args.frames is not None:
        frames = frame_corpus()
        frames_out = pathlib.Path(args.frames)
        frames_out.parent.mkdir(parents=True, exist_ok=True)
        frames_out.write_text("\n".join(json.dumps(v, sort_keys=True) for v in frames) + "\n",
                              encoding="utf-8")
        frame_counts: dict[str, int] = {}
        for vector in frames:
            frame_counts[vector["kind"]] = frame_counts.get(vector["kind"], 0) + 1
        print(f"generated {len(frames)} frame vectors into {frames_out}")
        print("  kinds: " + ", ".join(f"{k}={v}" for k, v in sorted(frame_counts.items())))
        print(f"  sha256: {hashlib.sha256(frames_out.read_bytes()).hexdigest()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
