#!/usr/bin/env python3
"""Generate a large value corpus for the reference implementation and the specification.

    scripts/gen-value-vectors.py [--out vectors/generated.ndjson]

The corpus has three families, and the *provenance of each expectation* is what
makes it worth having:

* **golden** — a value is encoded by this script's own encoder and the octets are
  asserted. The encoder is a third transcription of Part 1's encoding rules,
  written from the artifact's table and checked at import time against the
  worked examples the artifact publishes (the str8 example, the described-URL
  example and the composite `book` value). It is neither the Lean implementation
  nor the specification, so a vector it disagrees with is a real question.
* **reject** — malformed inputs: the reserved octets, the escape octets, every
  proper prefix of every golden vector (truncation), and size fields perturbed by
  one octet. Expectations here are properties of the grammar, not of an encoder.
* **property** — statements that need no oracle at all, over an exhaustive input
  domain: if a byte string decodes to a value, encoding that value must decode to
  the same value. Every input of one and two octets is emitted, so the domain is
  closed rather than sampled.

Nothing is generated by running either Lean artefact: a corpus produced by the
thing under test would only show that it equals itself.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import sys
from xml.etree import ElementTree

ROOT = pathlib.Path(__file__).resolve().parent.parent
ARTIFACT = ROOT / "spec" / "oasis" / "amqp-core-types-v1.0-os.xml"
WIDTHS_ANCHOR = "amqp-core-types-v1.0-os.xml#picture.5"
ARRAY_ANCHOR = "amqp-core-types-v1.0-os.xml#picture.9"
COMPOUND_ANCHOR = "amqp-core-types-v1.0-os.xml#picture.8"
DESCRIBED_ANCHOR = "amqp-core-types-v1.0-os.xml#picture.2"
STRING_ANCHOR = "amqp-core-types-v1.0-os.xml#picture.1"

# ---------------------------------------------------------------- the encoder


def be(n: int, width: int) -> bytes:
    return n.to_bytes(width, "big")


def enc_uint(n: int) -> bytes:
    if n == 0:
        return bytes([0x43])
    if n <= 0xFF:
        return bytes([0x52, n])
    if n <= 0xFFFFFFFF:
        return bytes([0x70]) + be(n, 4)
    raise ValueError("uint out of range")


def enc_ulong(n: int) -> bytes:
    if n == 0:
        return bytes([0x44])
    if n <= 0xFF:
        return bytes([0x53, n])
    if n <= 0xFFFFFFFFFFFFFFFF:
        return bytes([0x80]) + be(n, 8)
    raise ValueError("ulong out of range")


def enc_int(n: int) -> bytes:
    if -(2**31) <= n < 2**31:
        return bytes([0x71]) + be(n % 2**32, 4)
    raise ValueError("int out of range")


def enc_long(n: int) -> bytes:
    if -(2**63) <= n < 2**63:
        return bytes([0x81]) + be(n % 2**64, 8)
    raise ValueError("long out of range")


def enc_variable(narrow: int, wide: int, payload: bytes) -> bytes:
    if len(payload) <= 0xFF:
        return bytes([narrow, len(payload)]) + payload
    return bytes([wide]) + be(len(payload), 4) + payload


def encode(value: dict) -> bytes:
    kind = value["type"]
    if kind == "null":
        return bytes([0x40])
    if kind == "boolean":
        return bytes([0x41 if value["value"] else 0x42])
    if kind == "ubyte":
        return bytes([0x50, value["value"]])
    if kind == "byte":
        return bytes([0x51, value["value"] % 256])
    if kind == "ushort":
        return bytes([0x60]) + be(value["value"], 2)
    if kind == "short":
        return bytes([0x61]) + be(value["value"] % 2**16, 2)
    if kind == "uint":
        return enc_uint(value["value"])
    if kind == "int":
        return enc_int(value["value"])
    if kind == "ulong":
        return enc_ulong(value["value"])
    if kind == "long":
        return enc_long(value["value"])
    if kind == "string":
        return enc_variable(0xA1, 0xB1, value["text"].encode())
    if kind == "symbol":
        return enc_variable(0xA3, 0xB3, value["text"].encode())
    if kind == "binary":
        return enc_variable(0xA0, 0xB0, bytes.fromhex(value["hex"]))
    if kind == "described":
        return bytes([0x00]) + encode(value["descriptor"]) + encode(value["value"])
    if kind == "list":
        body = b"".join(encode(item) for item in value["items"])
        if not value["items"]:
            return bytes([0x45])
        count = len(value["items"])
        # The size counts the octets after it: the count field (whose width
        # depends on the form) then the items.
        if 1 + len(body) <= 0xFF and count <= 0xFF:
            return bytes([0xC0, 1 + len(body), count]) + body
        return bytes([0xD0]) + be(4 + len(body), 4) + be(count, 4) + body
    if kind == "array":
        ctor = int(value["constructor"], 16)
        elements = b"".join(element_data(ctor, item) for item in value["items"])
        count = len(value["items"])
        if 2 + len(elements) <= 0xFF and count <= 0xFF:
            return bytes([0xE0, 2 + len(elements), count, ctor]) + elements
        return (bytes([0xF0]) + be(5 + len(elements), 4) + be(count, 4)
                + bytes([ctor]) + elements)
    raise ValueError(f"unknown value type {kind!r}")


def element_data(constructor: int, value: dict) -> bytes:
    """Array element data, in the array's declared constructor form.

    The array states its element constructor once, so each element's data is in
    that form — not in whatever form the element would choose alone.
    """
    kind = value["type"]
    if constructor in (0x40, 0x41, 0x42):
        return b""
    if constructor == 0x50 and kind == "ubyte":
        return bytes([value["value"]])
    if constructor == 0x70 and kind == "uint":
        return be(value["value"], 4)
    if constructor == 0x80 and kind == "ulong":
        return be(value["value"], 8)
    if constructor == 0x60 and kind == "ushort":
        return be(value["value"], 2)
    if constructor == 0xA1 and kind == "string":
        payload = value["text"].encode()
        return bytes([len(payload)]) + payload if len(payload) <= 0xFF else be(len(payload), 4) + payload
    if constructor == 0xA3 and kind == "symbol":
        payload = value["text"].encode()
        return bytes([len(payload)]) + payload if len(payload) <= 0xFF else be(len(payload), 4) + payload
    if constructor == 0xA0 and kind == "binary":
        payload = bytes.fromhex(value["hex"])
        return bytes([len(payload)]) + payload if len(payload) <= 0xFF else be(len(payload), 4) + payload
    return encode(value)[1:]


# ------------------------------------------------- the artifact's own examples


def artifact_examples() -> list[tuple[str, dict, bytes]]:
    """The worked examples Part 1 publishes, as (name, value, octets)."""
    hello = "Hello Glorious Messaging World"
    url = "http://example.org/hello-world"
    title = "AMQP for & by Dummies"
    a1 = "Rob J. Godfrey"
    a2 = "Rafael H. Schloming"
    book = "example:book:list"
    book_value = {
        "type": "described",
        "descriptor": {"type": "symbol", "text": book},
        "value": {
            "type": "list",
            "items": [
                {"type": "string", "text": title},
                {"type": "array", "constructor": "a1",
                 "items": [{"type": "string", "text": a1}, {"type": "string", "text": a2}]},
                {"type": "null"},
            ],
        },
    }
    return [
        ("str8-hello", {"type": "string", "text": hello},
         bytes([0xA1, 0x1E]) + hello.encode()),
        ("described-url", {"type": "described", "descriptor": {"type": "string", "text": "URL"},
                           "value": {"type": "string", "text": url}},
         bytes([0x00, 0xA1, 0x03]) + b"URL" + bytes([0xA1, 0x1E]) + url.encode()),
        ("book-composite", book_value, bytes.fromhex(
            "00" "a311" + book.encode().hex() + "c04003" + "a115" + title.encode().hex()
            + "e02502" + "a10e" + a1.encode().hex() + "13" + a2.encode().hex() + "40")),
    ]


def self_check() -> None:
    """The generator must reproduce the artifact's examples, or it is not trusted."""
    for name, value, expected in artifact_examples():
        produced = encode(value)
        if produced != expected:
            raise SystemExit(
                f"gen-value-vectors: the encoder disagrees with the artifact's {name} example\n"
                f"  artifact: {expected.hex()}\n  produced: {produced.hex()}"
            )


# ------------------------------------------------------------------- families

DESCRIPTOR_SYMBOL = {"type": "symbol", "text": "amqp:example"}
DESCRIPTOR_ULONG = {"type": "ulong", "value": 0x00000000_00000001}


def golden() -> list[dict]:
    vectors: list[dict] = []

    def add(name: str, value: dict, anchor: str, note: str) -> None:
        vectors.append({
            "vector": f"gen-{name}", "kind": "encode", "clauses": [anchor],
            "bytes": encode(value).hex(), "value": value, "note": note,
        })
        vectors.append({
            "vector": f"gen-{name}-decode", "kind": "decode", "clauses": [anchor],
            "bytes": encode(value).hex(), "value": value, "canonical": True,
            "note": f"{note} (decoding direction)",
        })

    # Scalar boundaries. Every width is exercised on both sides of each boundary,
    # because that is where a narrowest-encoding rule and a size field disagree.
    for label, values, anchor in (
        ("ubyte", [0, 1, 127, 128, 255], WIDTHS_ANCHOR),
        ("byte", [-128, -1, 0, 1, 127], WIDTHS_ANCHOR),
        ("ushort", [0, 1, 255, 256, 32767, 65535], WIDTHS_ANCHOR),
        ("short", [-32768, -1, 0, 32767], WIDTHS_ANCHOR),
        ("uint", [0, 1, 254, 255, 256, 65535, 65536, 2**31 - 1, 2**32 - 1], WIDTHS_ANCHOR),
        ("int", [-(2**31), -1, 0, 2**31 - 1], WIDTHS_ANCHOR),
        ("ulong", [0, 1, 255, 256, 2**32 - 1, 2**32, 2**63, 2**64 - 1], WIDTHS_ANCHOR),
        ("long", [-(2**63), -1, 0, 2**63 - 1], WIDTHS_ANCHOR),
    ):
        for value in values:
            add(f"{label}-{value}", {"type": label, "value": value}, anchor,
                f"{label} value {value}, encoded in the narrowest form that carries it")

    add("null", {"type": "null"}, DESCRIBED_ANCHOR, "the null value")
    add("boolean-true", {"type": "boolean", "value": True}, WIDTHS_ANCHOR, "true")
    add("boolean-false", {"type": "boolean", "value": False}, WIDTHS_ANCHOR, "false")

    # Variable-width payloads: the 8-to-32-bit length boundary is where a writer
    # must switch form and a reader must not.
    for label, length in (("empty", 0), ("one", 1), ("short", 254), ("max8", 255),
                          ("over8", 256), ("large", 70000)):
        text = "x" * length
        add(f"string-{label}", {"type": "string", "text": text}, STRING_ANCHOR,
            f"a string of {length} octets")
        add(f"symbol-{label}", {"type": "symbol", "text": text}, STRING_ANCHOR,
            f"a symbol of {length} octets")
        add(f"binary-{label}", {"type": "binary", "hex": ("ab" * length)},
            STRING_ANCHOR, f"binary data of {length} octets")

    # Compounds: counts at the 8-bit boundary, sizes across it, nesting.
    for count in (0, 1, 2, 254, 255, 256, 300):
        items = [{"type": "ubyte", "value": i % 256} for i in range(count)]
        add(f"list-{count}", {"type": "list", "items": items}, COMPOUND_ANCHOR,
            f"a list of {count} booleans")
    for count in (0, 1, 2, 255, 256):
        items = [{"type": "string", "text": "e" * 40} for _ in range(count)]
        add(f"array-strings-{count}",
            {"type": "array", "constructor": "a1", "items": items}, ARRAY_ANCHOR,
            f"an array of {count} strings")
    add("array-null", {"type": "array", "constructor": "40",
                       "items": [{"type": "null"}, {"type": "null"}]}, ARRAY_ANCHOR,
        "an array of nulls, whose elements carry no data at all")
    add("list-nested",
        {"type": "list", "items": [
            {"type": "list", "items": [{"type": "uint", "value": 7}]},
            {"type": "array", "constructor": "70",
             "items": [{"type": "uint", "value": 1}, {"type": "uint", "value": 2}]},
            {"type": "described", "descriptor": DESCRIPTOR_SYMBOL, "value": {"type": "null"}},
        ]}, COMPOUND_ANCHOR, "a list containing a list, an array and a described value")
    add("described-symbol", {"type": "described", "descriptor": DESCRIPTOR_SYMBOL,
                             "value": {"type": "string", "text": "payload"}},
        DESCRIBED_ANCHOR, "a described value with a symbolic descriptor")
    add("described-numeric", {"type": "described", "descriptor": DESCRIPTOR_ULONG,
                              "value": {"type": "list", "items": []}},
        DESCRIBED_ANCHOR, "a described value with a numeric descriptor, wrapping the empty list")
    return vectors


def rejects(golden_vectors: list[dict]) -> list[dict]:
    vectors: list[dict] = []

    # Every octet below the format-code ranges, and the twelve escape octets.
    for code in range(0x01, 0x40):
        vectors.append({
            "vector": f"gen-reserved-{code:02x}", "kind": "reject",
            "clauses": [WIDTHS_ANCHOR], "bytes": f"{code:02x}",
            "expectError": {"condition": "amqp:decode-error", "endpoint": "connection"},
            "note": f"0x{code:02X} lies below every format-code range",
        })
    for code in (0x4F, 0x5F, 0x6F, 0x7F, 0x8F, 0x9F, 0xAF, 0xBF, 0xCF, 0xDF, 0xEF, 0xFF):
        vectors.append({
            "vector": f"gen-escape-{code:02x}", "kind": "reject",
            "clauses": ["amqp-core-types-v1.0-os.xml#picture.3"], "bytes": f"{code:02x}00",
            "expectError": {"condition": "amqp:decode-error", "endpoint": "connection"},
            "note": f"0x{code:02X} is an escape octet reserved for future formats",
        })

    # Every proper prefix of every golden encoding must be rejected as truncated.
    for entry in golden_vectors:
        octets = bytes.fromhex(entry["bytes"])
        if len(octets) < 2 or len(octets) > 40:
            continue                      # keep the sweep to short vectors
        for cut in range(1, len(octets)):
            vectors.append({
                "vector": f"trunc-{entry['vector']}-{cut}", "kind": "reject",
                "clauses": entry["clauses"],
                "bytes": octets[:cut].hex(),
                "expectError": {"condition": "amqp:decode-error", "endpoint": "connection"},
                "note": f"the first {cut} of {len(octets)} octets of {entry['vector']}",
            })

    # Size fields perturbed by one octet, for compound and array encodings.
    for entry in golden_vectors:
        octets = bytearray.fromhex(entry["bytes"])
        value = entry.get("value", {})
        if value.get("type") == "list" and len(octets) >= 3 and octets[0] in (0xC0, 0xD0):
            for delta in (-1, 1):
                if octets[0] == 0xC0:
                    perturbed = bytearray(octets)
                    perturbed[1] = (perturbed[1] + delta) % 256
                else:
                    size = int.from_bytes(octets[1:5], "big") + delta
                    perturbed = bytearray(octets[:1]) + size.to_bytes(4, "big") + octets[5:]
                vectors.append({
                    "vector": f"size{delta:+d}-{entry['vector']}", "kind": "reject",
                    "clauses": entry["clauses"], "bytes": bytes(perturbed).hex(),
                    "expectError": {"condition": "amqp:decode-error", "endpoint": "connection"},
                    "note": f"{entry['vector']} with its size field moved by {delta}",
                })
    return vectors


def properties() -> list[dict]:
    """Exhaustive short inputs, asserting a law that needs no oracle.

    If a byte string decodes to a value, encoding that value must decode to the
    same value. Inputs that fail to decode make no claim, so the whole space of
    one- and two-octet inputs can be swept without an expected answer for each.
    """
    vectors: list[dict] = []
    for first in range(256):
        vectors.append({
            "vector": f"prop-{first:02x}", "kind": "property",
            "property": "decode-stable", "clauses": [WIDTHS_ANCHOR],
            "bytes": f"{first:02x}",
        })
    for first in range(256):
        for second in range(256):
            vectors.append({
                "vector": f"prop-{first:02x}{second:02x}", "kind": "property",
                "property": "decode-stable", "clauses": [WIDTHS_ANCHOR],
                "bytes": f"{first:02x}{second:02x}",
            })
    return vectors


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", default=str(ROOT / "vectors" / "generated.ndjson"))
    parser.add_argument("--limit-properties", type=int, default=None,
                        help="emit only the first N property vectors, for a quick pass")
    args = parser.parse_args(argv)

    self_check()
    gold = golden()
    corpus = gold + rejects(gold) + properties()
    if args.limit_properties is not None:
        props = [v for v in corpus if v["kind"] == "property"]
        corpus = [v for v in corpus if v["kind"] != "property"] + props[:args.limit_properties]

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(json.dumps(v, sort_keys=True) for v in corpus) + "\n",
                   encoding="utf-8")
    counts: dict[str, int] = {}
    for vector in corpus:
        counts[vector["kind"]] = counts.get(vector["kind"], 0) + 1
    digest = hashlib.sha256(out.read_bytes()).hexdigest()
    print(f"generated {len(corpus)} vectors into {out}")
    print("  kinds: " + ", ".join(f"{k}={v}" for k, v in sorted(counts.items())))
    print(f"  artifact: {hashlib.sha256(ARTIFACT.read_bytes()).hexdigest()[:16]}… "
          f"(the table the encoder was read from)")
    print(f"  sha256: {digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
